### ISSUE TITLE
:)

### ISSUE THREAD

**Issue by cowboysdude** [mykle1/MMM-VoiceControlMe#1]
Soooooooooooooooo that's what you're going for for a name?  Okkkkkkkkkkkkk   MMM-VoiceControl would have sounded so much better........ LOL

**Comment by TheStigh** [comment]
> Soooooooooooooooo that's what you're going for for a name? Okkkkkkkkkkkkk MMM-VoiceControl would have sounded so much better........ LOL

...and we can still change it :)
